### ISSUE TITLE
panic recovered: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by lolseru** [everstu/Koolcenter_alist#1]
alist 版本3.4.1 执行copy时系统报错：
2022/11/25 13:16:42 [Recovery] 2022/11/25 - 13:16:42 panic recovered:
unaligned 64-bit atomic operation
/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 (0x179ef)
/usr/local/go/src/runtime/internal/atomic/atomic_arm.s:258 (0x17d5b)
/source/internal/fs/copy.go:19 (0xaec2ef)
/source/pkg/task/manager.go:19 (0x51389b)
/source/internal/fs/copy.go:38 (0xaec743)
/source/internal/fs/fs.go:60 (0xaedffb)
/source/server/handles/fsmanage.go:112 (0xb29357)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0xc684d7)
/source/server/middlewares/auth.go:55 (0xc682e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0xc68807)
/source/server/middlewares/check.go:11 (0xc68794)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0x827367)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/recovery.go:101 (0x827344)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0x826443)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/logger.go:240 (0x826420)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0x8253b3)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616 (0x8250a8)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572 (0x824c83)
/usr/local/go/src/net/http/server.go:2947 (0x36866f)
/usr/local/go/src/net/http/server.go:1991 (0x363b7b)
/usr/local/go/src/runtime/asm_arm.s:831 (0x90d77)

[GIN] 2022/11/25 - 13:16:42 | 500 |    1.587901ms |  192.168.50.110 | POST     "/api/fs/copy"

接入aria2插件后，离线下载功能也是失败的

**Comment by everstu** [comment]
这个是二进制那边的问题哦。

目前华硕路由器部分低版本系统无法使用3.5.1版本，所以不确定351是否修复该问题。

**Comment by lolseru** [comment]
我在alist群咨询后得到如下解决方案：
wget https://github.com/alist-org/alist/releases/download/v3.5.1/alist-linux-musl-arm64.tar.gz
tar -zxvf alist-linux-musl-arm64.tar.gz
chmod -x alist

我将这个alist 替换了在/koolshare/bin下的alist 解决了这个问题

**Comment by everstu** [comment]
> 



> 我在alist群咨询后得到如下解决方案： wget https://github.com/alist-org/alist/releases/download/v3.5.1/alist-linux-musl-arm64.tar.gz tar -zxvf alist-linux-musl-arm64.tar.gz chmod -x alist
> 
> 我将这个alist 替换了在/koolshare/bin下的alist 解决了这个问题

OK 好的 后续alist插件二进制我替换成这个版本 感谢反馈！
