### ISSUE TITLE
更新1.4.1版本后无法开启alilst进程

### ISSUE THREAD

**Issue by zhanghaotianle** [everstu/Koolcenter_alist#10]
使用前期版本没有问题，刚才升级为1.4.1版本后点击启用，运行状态为alist进程未运行。查看运行日志报错为：failed to connect database:disk I/O error: invalid argument 
补充信息：使用AC86U安装

**Comment by liujc139** [comment]
同样的问题，升级1.4.1无法启动alilst

**Comment by roc29a** [comment]
同样的问题，升级1.4.1无法启动alilst
补充信息：使用RT-AX86U安装

**Comment by everstu** [comment]
二进制兼容问题，已回退3.8.0版本二进制。
