### ISSUE TITLE
AC86U重启后 Alist不自动开启

### ISSUE THREAD

**Issue by dchl311** [everstu/Koolcenter_alist#13]
AC86U重启后 Alist不自动开启 需要手动开启  不知道是我路由的问题还是软件的问题

**Comment by everstu** [comment]
能否提供日志信息呢？

**Comment by dchl311** [comment]
hi 感谢回复

录了个重启演示的视频，见
https://github.com/dchl311/KHDFX/blob/master/AC86U%E9%87%8D%E5%90%AF%E8%A7%86%E9%A2%91.mp4
日志在视频里有打开，麻烦帮忙看下，如有方法解决，不胜感激

其中aria2和Alist不能自启，其它几个插件都可以，感觉应该是虚拟内存的原因

如需提供其它日志，麻烦告诉我日志所在的文件路径，我下载给你

谢谢



***@***.***
 
发件人： everstu
发送时间： 2023-02-10 12:01
收件人： everstu/Koolcenter_alist
抄送： dchl311; Author
主题： Re: [everstu/Koolcenter_alist] AC86U重启后 Alist不自动开启 (Issue #13)
能否提供日志信息呢？

**Comment by everstu** [comment]
感谢反馈~
看起来像是虚拟内存启动检测问题，因为内存低于1G的机型被要求强制开启虚拟内存，导致虚拟内存未自动挂载之前自启失败，下版本尝试增加对应机型延迟启动参数来修复此问题。
