### ISSUE TITLE
是不是更新1.5之后只能运行在tmp目录？还有就是内存占用比之前大了不少。是不是正常的？

### ISSUE THREAD

**Issue by FopFat** [everstu/Koolcenter_alist#14]
1.5版本更新后，启动Alist，运行记录提示如下：
【2023年02月10日 22:30:04】: ▶️开启alist！
【2023年02月10日 22:30:04】: ℹ️检查系统内存是否合规！
【2023年02月10日 22:30:04】: ✅️当前系统已经启用虚拟内存！容量：1094300KB
【2023年02月10日 22:30:04】: ➡️生成alist配置文件到/koolshare/alist/config.json！
【2023年02月10日 22:30:04】: ⚠️[Tmp目录模式] Alist将运行在/tmp目录！
【2023年02月10日 22:30:06】: ➡️[Tmp目录模式] 复制alist数据库至使用目录！
【2023年02月10日 22:30:06】: ℹ️[Tmp目录模式] 创建alist数据库备份任务
【2023年02月10日 22:30:06】: 🆗证书校验通过！为alist面板启用https...
【2023年02月10日 22:30:08】: 🟠启动 alist 进程，开启进程实时守护...
【2023年02月10日 22:30:08】: 🟢alist启动成功，pid：16603
【2023年02月10日 22:30:08】: 🧱添加防火墙入站规则，打开alist端口：5244
--- 
设备AX86，是不是更新1.5之后只能运行在tmp目录？还有就是内存占用比之前大了不少。这些表现是不是正常的？还是需要设置什么？
求解，感谢。

**Comment by everstu** [comment]
是的，1.5之后只能在tmp目录运行，低内核路由器系统在非/tmp目录存在无法读取数据的错误。

另，内存占用这个问题要去看top命令实际占用，其实linux内存占用机制不用过于关心，linux系统内存如果有空闲内存会缓存起来换取更高的运行速度。

可以去看看官方文档或加入官方交流群，研究更优使用方案。

**Comment by FopFat** [comment]
对于我这种菜鸡用户，多谢答疑。对于软件，只会使用，有的时候使用都用不全功能。感谢更新，感谢编译成路由器能用的插件，十分感谢。
