### ISSUE TITLE
请问data.db如何重定向到usb存储

### ISSUE THREAD

**Issue by babylife** [everstu/Koolcenter_alist#15]
不确定是否支持，之前使用USBJFFS的时候，发现data.db有100Mb,后来使用内置JFFS的时候，发现/tmp/run_alist 下的data.db，不知道会不会越来越大，这个是索引文件吗？

**Comment by everstu** [comment]
这个是数据库文件，如果开启索引之后会导致这个文件越来越大越来越大。

**Comment by everstu** [comment]
最新版插件安装usb2jffs插件挂载到usb设备之后就可以自动回到正常运行模式了。
