### ISSUE TITLE
索引产生的DB文件存储位置可以开放设置吗

### ISSUE THREAD

**Issue by dchl311** [everstu/Koolcenter_alist#16]
DB文件比较大，如果可以开放存储位置，可以设定存储在USB挂载的盘里就好了，默认用aria2离线时下载的文件在temp下希望也能开放设置下载到USB挂载的盘里
![image](https://user-images.githubusercontent.com/47244445/218994759-c24ba1b7-f9f8-4f99-8122-1d954114133e.png)

**Comment by everstu** [comment]
v1.5.2 已更改逻辑，挂载usb2jffs后自动把db放到挂载的usb里。
