### ISSUE TITLE
插件设置界面可增加并发连接数设置

### ISSUE THREAD

**Issue by SkyDreamLG** [everstu/Koolcenter_alist#19]
当前插件自动生成的配置文件中并发连接数默认设置为不限制，当以图片视图或网格视图访问挂载为本地存储且存有较多高清图片的存储时路由极易因为压力过大而死机重启。可以增加并发连接数设置功能以提高插件稳定性

**Comment by everstu** [comment]
二进制问题请移步[Alist官方社区](https://github.com/alist-org/alist)反馈。

其他与插件无关问题请自行研究解决。
