### ISSUE TITLE
插件可增加性能占用限制功能

### ISSUE THREAD

**Issue by SkyDreamLG** [everstu/Koolcenter_alist#20]
当前插件在以图片视图或网格视图访问挂载为本地存储且存有较多高清图片的存储时极易因CPU占用过高而导致路由死机重启，可增加性能占用限制功能以提高插件稳定性

**Comment by everstu** [comment]
已经限制只允许HND路由器使用插件。

其他性能由用户自行决定是否使用。

PS：球球放过路由器，别把路由器当服务器用。

**Comment by everstu** [comment]
已经限制只允许HND路由器使用插件。

其他性能由用户自行决定是否使用。

PS：球球放过路由器，别把路由器当服务器用。
