### ISSUE TITLE
插件无法重建索引

### ISSUE THREAD

**Issue by SkyDreamLG** [everstu/Koolcenter_alist#21]
插件重建索引按钮点击后直接提示success，对象计数还是0不变，搜索提示：Failed get users count: database disk image is malformed。

Uploading 7nzLoMoDHD.mp4…

**Comment by everstu** [comment]
二进制问题请移步[Alist官方社区](https://github.com/alist-org/alist)反馈。

**Comment by everstu** [comment]
二进制问题请移步[Alist官方社区](https://github.com/alist-org/alist)反馈。
