### ISSUE TITLE
115还是无法播放，自从1.6.4版本之后，115一直无法播放

### ISSUE THREAD

**Issue by fanxu1218** [everstu/Koolcenter_alist#22]
115还是无法播放，自从1.6.4版本之后，115一直无法播放，楼主一直没修正呀

**Comment by everstu** [comment]
建议去查看alist官方手册，二进制问题及使用问题请自行解决。

**Comment by fanxu1218** [comment]
> 

不是二进制的问题，官方手册也看过了，就是不行呀

**Comment by fanxu1218** [comment]
> 建议去查看alist官方手册，二进制问题及使用问题请自行解决。

解决不了，刚才有出现可以播放一两部，后面还是都不能播放呢

**Comment by everstu** [comment]
> 

二进制及使用问题要去官方交流群咨询和寻求帮助，插件这边不提供使用帮助。
