### ISSUE TITLE
求支持armv7l架构

### ISSUE THREAD

**Issue by ACmagic** [everstu/Koolcenter_alist#23]
官方似乎已经支持了：https://github.com/alist-org/alist/issues/4243

**Comment by ACmagic** [comment]
![捕获](https://github.com/everstu/Koolcenter_alist/assets/6644559/3cb7ed20-64e0-414e-a9d9-7e167cb06cba)
试了一下还是不可以

**Comment by everstu** [comment]
> ![捕获](https://github.com/everstu/Koolcenter_alist/assets/6644559/3cb7ed20-64e0-414e-a9d9-7e167cb06cba)
> 试了一下还是不可以

升级路由器吧，384/386 ac系列性能太差 了。
