### ISSUE TITLE
如何更换自定义的alist二进制文件？

### ISSUE THREAD

**Issue by JustLookAtNow** [everstu/Koolcenter_alist#24]
我自己打包出来的都七八十兆，为啥这个项目里才17.6M？
起因是有人做了阿里云cdn加速下载的pr但是因为用的api不是阿里云官方文档里面的所以alist官方不愿意合并。
我就想着自己能把不能拿修改后的alist二进制替换下，结果一看大小差这么多我有点迷茫了。。
详见https://github.com/alist-org/alist/issues/6644

**Comment by everstu** [comment]
插件里二进制是经过upx压缩的。

压缩命令及指令可以看更新日志第一条。
