### ISSUE TITLE
Alist site_url 配置问题

### ISSUE THREAD

**Issue by JaxsonWang** [everstu/Koolcenter_alist#26]
目前我用服务器的 nginx 反代监听路由器 Alist 服务端口号为 444，并且配置新的域名为：`pan.example.com` 然后到 alist 配置 `site_url` 项发现报错：

<img width="615" alt="iShot_2024-11-06_10 16 37" src="https://github.com/user-attachments/assets/cbb67653-d676-4ff8-a4d9-7e7d31fe3c75">
<img width="753" alt="iShot_2024-11-06_10 16 56" src="https://github.com/user-attachments/assets/5ae34bdc-d4f3-4e06-b035-15ea6c0b87ce">

这里可否不要做限制？或者有什么其他方案呢？

**Comment by everstu** [comment]
我大概理解你的意思了，你是反代了Alist导致实际端口跟alist填写不一致。

这个端口号检测本质上是为路由插件设置的，下个版本我修改成提示错误，但是不阻止写入。

**Comment by everstu** [comment]
v2.1.0 已发布，site_url 修改成提示错误，但是不阻止写入。

**Comment by JaxsonWang** [comment]
好的，感谢🙏
