### ISSUE TITLE
速度被限制了

### ISSUE THREAD

**Issue by xiaoLit** [everstu/Koolcenter_alist#3]
我用的ax86u的梅林改固件，安装的0.6版本该插件。
测试通过该插件alist挂载阿里云盘，对比 aliyundrive-webdav 挂载阿里云盘。
同一个云盘同一部电影：alist插件挂载的阿里云盘当前速度会一直卡在63.96Mbps不会再高，而aliyundrive-webdav插件轻松达到150+Mbps。
能感觉到alist挂载明显限速。

**Comment by sadoneli** [comment]
有观察峰值速度的时候路由器CPU占用没？

**Comment by xiaoLit** [comment]
有的  4个核心占用率平均下来不到50%

**Comment by sadoneli** [comment]
aliyundrive-webdav这个是rust写的把，应该效率上会比golang写的alist效率更高

**Comment by xiaoLit** [comment]
换了软路由 用openwrt装的alist速度就上去了  直接150Mbps左右
