### ISSUE TITLE
关于公网的问题

### ISSUE THREAD

**Issue by nodesire7** [everstu/Koolcenter_alist#7]
每次开启公网后页面加载变慢 而且用公网也访问不了
不知道怎么回事。

**Comment by FopFat** [comment]
DDNS做好了？

**Comment by babylife** [comment]
检查端口映射吧

**Comment by everstu** [comment]
公网访问无问题，排查下你本地的网络环境，如果还是不行建议使用ddnsto内网穿透。

**Comment by nodesire7** [comment]
> 公网访问无问题，排查下你本地的网络环境，如果还是不行建议使用ddnsto内网穿透。

我的意思是把公网访问的按钮点开本地都不能访问了 ddns做好了 我的其他本地的东西都可以正常访问

**Comment by everstu** [comment]
> > 公网访问无问题，排查下你本地的网络环境，如果还是不行建议使用ddnsto内网穿透。
> 
> 我的意思是把公网访问的按钮点开本地都不能访问了 ddns做好了 我的其他本地的东西都可以正常访问

你是否配置的域名访问？域名访问是有这个问题，我本地用域名访问用mc配置路由器本地host把ddns域名IP改成路由器IP就行了，公网IP在本地是无法访问的。
